# Generated by Django 3.0 on 2021-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('translation_file', models.FileField(upload_to='translation_packs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
