# Generated by Django 3.0 on 2021-07-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210630_0804'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shilengaeuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.Country'),
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
