# Generated by Django 3.0 on 2021-07-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210706_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shilengaeuser',
            options={'ordering': ['first_name']},
        ),
    ]
