# Generated by Django 3.0 on 2021-07-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210710_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='shilengaeuser',
            name='type',
            field=models.CharField(choices=[('SUPERADMIN', 'SUPERADMIN'), ('ADMIN', 'ADMIN'), ('MODERATOR', 'MODERATOR'), ('GUEST', 'GUEST'), ('USER', 'USER')], default='GUEST', max_length=50),
        ),
    ]
