# Generated by Django 3.0 on 2021-09-09 18:34

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210807_1946'),
        ('users', '0004_shilengaeuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShilengaeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mobile_country_code', models.CharField(blank=True, max_length=5)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registration_method', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('facebook_id', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('online_status', models.BooleanField(default=False)),
                ('business_user', models.BooleanField(default=False)),
                ('verified_mobile', models.BooleanField(default=False)),
                ('verified_email', models.BooleanField(default=False)),
                ('verified_phone', models.BooleanField(default=False)),
                ('verified_facebook', models.BooleanField(default=False)),
                ('operating_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.Country')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
