# Generated by Django 3.0 on 2021-09-12 02:14

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shilengaeuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shilengaeuserprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shilengaeuserprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shilengaeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='ShilengaeUserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('app_notification', models.BooleanField(default=True)),
                ('chat_notification', models.BooleanField(default=True)),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
