# Generated by Django 3.0 on 2021-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210912_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shilengaeuser',
            name='firebase_uid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
