# Generated by Django 3.0 on 2021-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210912_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shilengaeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
