# Generated by Django 3.0 on 2021-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shilengaeuserprofile',
            name='mobile_country_code',
        ),
        migrations.RemoveField(
            model_name='shilengaeuserprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='mobile_country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='shilengaeuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
