# Generated by Django 3.0 on 2021-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211002_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shilengaeuser',
            name='mobile_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shilengaeuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
