# Generated by Django 3.0 on 2021-10-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211002_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shilengaeuserprofile',
            name='verified_mobile',
        ),
    ]
