# Generated by Django 3.0 on 2021-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_shilengaeuserprofile_verified_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shilengaeuserprofile',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('FACEBOOK', 'FACEBOOK'), ('REGULAR', 'REGULAR')], max_length=50),
        ),
    ]
