# Generated by Django 3.0 on 2021-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210807_1946'),
        ('users', '0014_auto_20211018_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='shilengaeuserprofile',
            name='operable_countries',
            field=models.ManyToManyField(blank=True, related_name='_shilengaeuserprofile_operable_countries_+', to='locations.Country'),
        ),
    ]
