# Generated by Django 3.0 on 2022-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_shilengaeuserprofile_operable_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='shilengaeuser',
            name='v1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
