# Generated by Django 3.0 on 2021-06-26 08:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('textbox', 'textbox'), ('multiline_textbox', 'multiline_textbox')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('hint', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('data', jsonfield.fields.JSONField()),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('form_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field', to='forms.FormField')),
            ],
        ),
    ]
