# Generated by Django 3.0 on 2021-07-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ancestors', models.ManyToManyField(related_name='_category_ancestors_+', to='forms.Category')),
                ('descendants', models.ManyToManyField(related_name='_category_descendants_+', to='forms.Category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='forms.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
