# Generated by Django 3.0 on 2021-07-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210710_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='forms.Form'),
        ),
    ]
