# Generated by Django 3.0 on 2021-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210711_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('position', 'form')},
        ),
    ]
