# Generated by Django 3.0 on 2021-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210719_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('textbox', 'textbox'), ('multiline_textbox', 'multiline_textbox'), ('dropdown', 'dropdown'), ('radio', 'radio'), ('multi-select', 'multi-select'), ('image', 'image'), ('file', 'file'), ('date', 'date'), ('date-range', 'date-range'), ('range', 'range')], max_length=50),
        ),
    ]
