# Generated by Django 3.0 on 2021-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210725_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
