# Generated by Django 3.0 on 2021-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formfield_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
