# Generated by Django 3.0 on 2021-08-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20210807_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('textbox', 'textbox'), ('multiline_textbox', 'multiline_textbox'), ('dropdown', 'dropdown'), ('radio', 'radio'), ('multi-select', 'multi-select'), ('image', 'image'), ('file', 'file'), ('date', 'date'), ('date-range', 'date-range'), ('range', 'range'), ('region', 'region'), ('city', 'city')], max_length=50),
        ),
    ]
