# Generated by Django 3.0 on 2021-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210817_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('textbox', 'textbox'), ('multiline_textbox', 'multiline_textbox'), ('dropdown', 'dropdown'), ('radio', 'radio'), ('multi-select', 'multi-select'), ('image', 'image'), ('file', 'file'), ('date', 'date'), ('date-range', 'date-range'), ('range', 'range'), ('region', 'region'), ('city', 'city'), ('price', 'price')], max_length=50),
        ),
    ]
