# Generated by Django 3.0 on 2021-09-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210807_1946'),
        ('forms', '0011_formfield_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='locations.Country'),
        ),
        migrations.AddField(
            model_name='form',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='locations.Country'),
        ),
    ]
