# Generated by Django 3.0 on 2021-10-07 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
        ('forms', '0012_auto_20210905_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldresponse',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='ads.Ad'),
        ),
        migrations.AddField(
            model_name='formfieldresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldresponse',
            unique_together={('form_field', 'user', 'ad')},
        ),
    ]
