# Generated by Django 3.0 on 2021-11-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20211025_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldImageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='form_field_image_responses')),
                ('form_field_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='forms.FormFieldResponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
