# Generated by Django 3.0 on 2022-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20211218_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_filterable',
            field=models.BooleanField(default=True),
        ),
    ]
