# Generated by Django 3.0 on 2022-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_formfield_is_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='v1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
