# Generated by Django 3.0 on 2022-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shilengaeissuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='category_version',
            field=models.IntegerField(default=0),
        ),
    ]
