# Generated by Django 3.0 on 2022-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appversion_category_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='max_android_version',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='appversion',
            name='max_ios_version',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='appversion',
            name='min_android_version',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='appversion',
            name='min_ios_version',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
