# Generated by Django 3.0 on 2021-10-12 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='favoriters',
            field=models.ManyToManyField(related_name='favorited_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
