# Generated by Django 3.0 on 2021-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20211020_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='adExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
