# Generated by Django 3.0 on 2021-11-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20211020_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShilengaeAdPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('adExpiryEnabled', models.BooleanField(default=False)),
                ('adExpiryDays', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
