# Generated by Django 3.0 on 2021-12-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_categoryiconpack'),
        ('ads', '0006_shilengaeadpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='forms.Category'),
        ),
    ]
