# Generated by Django 3.0 on 2021-12-21 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0007_auto_20211209_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedads',
            name='report_categtory',
            field=models.CharField(choices=[('HARASSMENT', 'HARASSMENT'), ('INADEQUATE LANGUAGE', 'INADEQUATE LANGUAGE'), ('FAKE', 'FAKE'), ('FRAUD', 'FRAUD'), ('OVERCHARGED', 'OVERCHARGED'), ('DUPLICATE', 'DUPLICATE'), ('ILLEGAL', 'ILLEGAL')], default='FRAUD', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reportedads',
            unique_together={('ad', 'user')},
        ),
    ]
