# Generated by Django 3.0 on 2022-02-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20211227_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='v1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
