# Generated by Django 3.0 on 2022-04-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_v1_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedads',
            old_name='report_categtory',
            new_name='report_category',
        ),
    ]
