# Generated by Django 3.0 on 2021-08-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210630_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='locations.Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='symbol',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='locations.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'symbol')},
        ),
    ]
